
/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <string>
#include <stdlib.h>
#include <unistd.h>
#include "json.hpp"
#include "dirhash.hpp"
#include "miniservant.h"

using json = nlohmann::json;

int main(int argc, char* argv[]) {
    auto p = std::filesystem::path("/");
    auto dh = miniservant::dirhash(p / "/home/takami/waffle/WAFFLE/LOCAL", p / "/home/takami/waffle/WAFFLE/LOCAL/PROJECT/test3/WORKSPACE/test1_300_1/RUN/sleep");
    std::cout << dh.directoryPath << std::endl;
    std::cout << dh.getHashFilePath() << std::endl;
    dh.save();
    

    std::string s = R"({ "happy": true, "pi": 3.141 } )";
    json j = json::parse(s);
    std::cout << j["pi"] << std::endl;
    std::cout << j.dump() << std::endl;
    //system("sleep 5");
    std::cout << argv[1] << std::endl;
    return 0;
}
