
/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include <iostream>
#include <string>
#include <stdlib.h>
#include <unistd.h>
#include "app.h"


int main(int argc, char* argv[]) {
    system("sleep 5");
    std::cout << argv[1] << std::endl;
    return 0;
}
