/*
 * This C++ source file was generated by the Gradle 'init' task.
 */

#include "miniservant.h"
#include <cassert>

int main() {
    /*
    miniservant::Greeter greeter;
    assert(greeter.greeting().compare("Hello, World!") == 0);
    */
    return 0;
}
